name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - main-lite-branch
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2
        with:
          linter: jetbrains/qodana-python:2024.2
          pr-mode: false
        env:
          QODANA_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0IjoiM0tHamEiLCJvcmdhbml6YXRpb24iOiJBR0JLWSIsInRva2VuIjoiQUdNRHIiLCJ0b2tlbl90eXBlIjoicHJvamVjdCJ9.ELm7ERJ29f6pkMTRpHf7Im6MDS1D0WwLcFRwZcWFHMs
          QODANA_ENDPOINT: 'https://qodana.cloud'
